language: go

go:
  - 1.14.x

git:
  # set clone depth to 3 to allow small buffer of commits to include in build job
  depth: 3

services:
  - docker

# no need to install dependencies. this is done in the container image build
install: skip

env:
  global:
    - TRAVIS_COMMIT_SHORT=$(echo $TRAVIS_COMMIT | cut -c-7)

script:
  - set -e && go test ./... && set +e
  - docker build -t srowley/game-room-service:$TRAVIS_COMMIT_SHORT -t srowley/game-room-service:latest .
  - docker run -d -p 8080:8080 --name game-room-service srowley/game-room-service:$TRAVIS_COMMIT_SHORT
  - docker ps | grep -q game-room-service

after_success:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push srowley/game-room-service:$TRAVIS_COMMIT_SHORT
  - docker push srowley/game-room-service:latest
